---
# tasks file for httpd

- name: import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install apache httpd
  ansible.builtin.package:
    name: "{{ httpd_packages }}"
    state: present

- name: configure selinux
  block:
    - name: modify selinux settings
      ansible.posix.seboolean:
        name: "{{ item }}"
        state: yes
        persistent: yes
      when:
        - ansible_selinux.status is defined
        - ansible_selinux.status == "enabled"
      loop: "{{ httpd_sebooleans }}"

    - name: allow connections to custom port
      community.general.seport:
        ports: "{{ item }}"
        proto: tcp
        setype: http_port_t
        state: present
      loop:
        - "{{ httpd_port }}"
        - "{{ httpd_ssl_port | default(omit) }}"
  when:
    - ansible_selinux.status is defined
    - ansible_selinux.status == "enabled"

- name: configure ssl
  block:
    - name: install ssl packages
      package:
        name: "{{ httpd_ssl_packages }}"
        state: present
    - name: place configuration
      ansible.builtin.template:
        src: ssl.conf.j2
        dest: "{{ httpd_config_directory }}/ssl.conf"
        mode: "0644"
      notify:
        - test httpd configuration validity
        - restart httpd
    - name: configure redirect from http to https
      ansible.builtin.template:
        src: default_vhost.conf.j2
        dest: "{{ httpd_config_directory }}/default_vhost.conf"
        mode: "0644"
      notify:
        - test httpd configuration validity
        - restart httpd
  when:
    - https_ssl_enable

- name: configure locations
  ansible.builtin.template:
    src: location.conf.j2
    dest: "{{ httpd_config_directory }}/{{ item.name }}.conf"
    mode: "0644"
  loop: "{{ httpd_locations }}"
  loop_control:
    label: "{{ item.name }}"
  notify:
    - test httpd configuration validity
    - restart httpd
  when:
    - httpd_locations is defined

- name: configure vhosts
  ansible.builtin.template:
    src: "{{ item.template | default('vhost') }}.conf.j2"
    dest: "{{ httpd_config_directory }}/{{ item.name }}.conf"
    mode: "0644"
  loop: "{{ httpd_vhosts }}"
  loop_control:
    label: "{{ item.name }}"
  notify:
    - test httpd configuration validity
    - restart httpd
  when:
    - httpd_vhosts is defined

- name: configure httpd
  ansible.builtin.template:
    src: "{{ httpd_config_src }}"
    dest: "{{ httpd_config_dest }}"
    mode: "0644"
  notify:
    - test httpd configuration validity
    - restart httpd

- name: configure listening ports
  ansible.builtin.template:
    src: "{{ httpd_ports_conf }}.j2"
    dest: "{{ httpd_server_root }}/{{ httpd_ports_conf }}"
    mode: "0644"
  notify:
    - test httpd configuration validity
    - restart httpd
  when:
    - ansible_os_family in [ "Debian", "Suse" ]

- name: create docroot
  ansible.builtin.file:
    path: "{{ item.documentroot }}"
    state: directory
    mode: "0755"
  loop: "{{ httpd_vhosts }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - httpd_vhosts is defined
    - item.documentroot is defined

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: start and enable httpd
  ansible.builtin.service:
    name: "{{ httpd_service }}"
    state: started
    enabled: yes
